### PR TITLE
[PATCH v3] doc: images: correct packet segment diagram

### PR DESCRIPTION
**Pull request by Bill-Fischofer-Linaro**
Fix Bug https://bugs.linaro.org/show_bug.cgi?id=3043 by correcting
the packet segment diagram to reflect the correct APIs:
odp_packet_l2_ptr(), odp_packet_l3_ptr(), and odp_packet_l4_ptr().

Signed-off-by: Bill Fischofer <bill.fischofer@linaro.org>

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
@lumag This is a trivial fix patch. Would appreciate you giving it a quick look / review so this bug can be closed. Thanks.

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro could you please describe, what exactly are you correcting.
Also while you are at it, could you please change seglen, so that it will point to the whole segment (e.g. seg1).

**Comment by muvarov** [comment]
if in this pull request you click on files, then on "view" it will redirect you to link with hole file:
https://github.com/Bill-Fischofer-Linaro/odp/blob/ce43c81d1e3ddb702defb0438dc74c16cc6fa512/doc/images/segment.svg

**Comment by Bill-Fischofer-Linaro** [comment]
I'll update the commit msg, but not sure what you're asking with regard to seglen. seglen is an output parameter from the odp_packet_lx_ptr() and gives the number of bytes from the returned pointer to the end of the segment (in this case Segment 0). It defines how many bytes are contiguously addressable from the returned pointer.

**Comment by Bill-Fischofer-Linaro** [comment]
@muvarov Thanks, Maxim! That's a nice feature of GitHub that I hadn't noticed. Good to point that out.

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v2:
- Rebased to current master
- Expanded commit msg to reflect @lumag comments

**Comment by Bill-Fischofer-Linaro** [comment]
@muvarov Strange. This branch passed Travis in my repo, then the PR failed the clang --disable-abi-compat test, but when I asked that test to be restarted it passed. Are we seeing intermittent failures on that test elsewhere?

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro https://travis-ci.org/Linaro/odp/builds if it was stopped with "!" mark, than in means or test hung or Travis power down execution node. Power down is more likely action. I see number of build were marked as "!", might be some internal maintenance.

**Comment by lumag** [comment]
Looks good now, thanks.
Reviewed-by: Dmitry Eremin-Solenikov

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro  Merged with a little rewording commit message. Commit should describe which actual issue is fixed, not that bug number is fixed. And link to bug should be there for people who need more info for that problem.

**Pull request closed without merging**
