### PR TITLE
[PATCH v1] crypto: support SHA384 and AES-XCBC algorithm in ipsec-odp

### PR DESCRIPTION
**Pull request by SonicwallYhe**

### CODE REVIEW

**Comment by muvarov** [comment]
@lumag  PR needs rebase.

**Comment by lumag** [comment]
@SonicwallYhe probably you missed several commits here. Also this PR will include API changes (XCBC is not defined yet), so it should be sumitted against api-next.
@muvarov this is not mine PR.

**Comment by muvarov** [comment]
@lumag sorry. I'm used to getting  ipsec patches can from you :)

**Comment by muvarov** [comment]
On top of the page is says  Linaro:master from SonicwallYhe:api-next . I.e. when you created web interface you should specify destination branch api-next. Not master.

**Comment by Bill-Fischofer-Linaro** [comment]
Superseded by PR #422

**Pull request closed without merging**
