### PR TITLE
[PATCH API-NEXT v19] test: validation: add IPsec API testsuite

### PR DESCRIPTION
**Pull request by lumag**
Add several basic tests for IPsec API.

This PR incorporates #69  and event subtypes implementation on which it depends.

### CODE REVIEW

**Comment by NikhilA-Linaro** [comment]
1. odp_ipsec_config API is to be called once per application, can not be called again and again from same application.
2. Disable events are for inline ipsec operations only.
3. Event queue(for SA disable events) and SA completion queue can not be same.

**Comment by lumag** [comment]
@NikhilA-Linaro 

Thanks for the review.

1. I will update the testsuite. We should update docs to mention it however.
2. No. Disable event is sent for ASYNC and INLINE modes. See `odp_ipsec_sa_disable()` description.
3. Hmm. Quoting the doxygen doc: `In asynchronous mode, the same is indicated by an ODP_EVENT_IPSEC_STATUS event sent to the queue specified for the SA.` If this is not the case for your implementation, we should update docs and/or add another capability.

**Comment by lumag** [comment]
@NikhilA-Linaro I'm still working on fixing multiple calls to `odp_ipsec_config()`. Currently I updated two IPsec pull-requests to include scheduler/queue fixes and initial AES-GCM support.

**Comment by Bill-Fischofer-Linaro** [comment]
Ping to @NikhilA-Linaro and @bala-manoharan. Still need a review for this PR.

**Comment by Bill-Fischofer-Linaro** [comment]
Ping to @NikhilA-Linaro and @bala-manoharan for review.

**Comment by muvarov** [comment]
<pre>
CHECK: Alignment should match open parenthesis
#2585: FILE: test/common_plat/validation/api/ipsec/test_vectors.h:46:
+KEY(key_mcgrew_gcm_12, 0x7d, 0x77, 0x3d, 0x00, 0xc1, 0x44, 0xc5, 0x25,
+		       0xac, 0x61, 0x9d, 0x18, 0xc8, 0x4a, 0x3f, 0x47);

is better to split on 3 lines:
KEY(key_mcgrew_gcm_12, 
    0x7d, 0x77, 0x3d, 0x00, 0xc1, 0x44, 0xc5, 0x25,
    0xac, 0x61, 0x9d, 0x18, 0xc8, 0x4a, 0x3f, 0x47);
</pre>

**Comment by lumag** [comment]
@muvarov not really:

```
WARNING: please, no spaces at the start of a line
#18: FILE: ./test/common_plat/validation/api/ipsec/test_vectors.h:18:
+    0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5,$

WARNING: please, no spaces at the start of a line
#19: FILE: ./test/common_plat/validation/api/ipsec/test_vectors.h:19:
+    0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5, 0xa5);$
```

**Comment by lumag** [comment]
Merged as a part of main PR

**Pull request closed without merging**
