### PR TITLE
[PATCH v4] linux-gen: Use /proc/cpuinfo, if sysfs is not available to get cpu info.

### PR DESCRIPTION
**Pull request by apalos**
PR#171 broke some of the functionality we had on getting cpu speed.
This patch reverts parts of that commit adding a fallback when
/sys/devices/system/cpu/cpuX/cpufreq/ is not available.

Solves https://bugs.linaro.org/show_bug.cgi?id=3249

Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>

### CODE REVIEW

**Comment by apalos** [comment]
v2->rebase

**Comment by apalos** [comment]
v4->rebase + fix on function declaration for x86

**Comment by apalos** [comment]
@Bill-Fischofer-Linaro He just updated the bugzilla entry as well.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
