### PR TITLE
[PATCH CATERPILLAR v1] Move packet to modular framework

### PR DESCRIPTION
**Pull request by kevinwangsk**
Include two commits. One is to apply the modular framework for packet module. The second one is to move the Linux-generic implementation to the modular framework.

### CODE REVIEW

**Comment by psavol** [comment]
This is actually a Caterpillar patch. It should show up as "PATCH CATERPILLAR v1".

**Comment by lumag** [comment]
@muvarov is something wrong with your scripts?

**Comment by heyi-linaro** [comment]
@Bill-Fischofer-Linaro @nagarahalli yes, let's talk in tomorrow's call whether it is time to do api-next merge into caterpillar and after then update this PR?

**Comment by heyi-linaro** [comment]
Close this PR due to high level decision

**Pull request closed without merging**
