### PR TITLE
[PATCH v2] api-next merge to 2.0 branch

### PR DESCRIPTION
**Pull request by nagarahalli**
api-next (snap shot on 10/11/2017) merge to 2.0

### CODE REVIEW

**Comment by bogdanPricope** [comment]
Can you re-run Job #1110.10? There are no logs but is marked as Failed.

**Comment by nagarahalli** [comment]
@bogdanPricope I do not have the permission to re-start the test, it is not giving me the option.
@muvarov Can you check if you can re-start the failing test in Travis?

**Comment by nagarahalli** [comment]
Build is passing after the re-run. The checkpatch issues are due to other commits that are getting merged.

**Comment by Bill-Fischofer-Linaro** [comment]
I don't understand why patch 0009 is generating the flurry of checkpatch warnings, as it doesn't contain any of the items that are being flagged. GitHub also says this needs to be rebased, but I'm not sure what the mechanics of these types of resync merges are. If @muvarov is OK with this, I'm OK.

**Pull request merged**
