### PR TITLE
linux-generic: crypto: properly handle errors in packet copy

### PR DESCRIPTION
**Pull request by lumag**
Add proper handling for errors returned by odp_packet_copy_from_pkt().

Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro again this is a question of having checks. I have stumbled upon this, because during example development I ended up with ODP_PACKET_INVALID in out_pkt and strange crash which took me some time to debug. So I'd prefer to have a check, rather than not to.

**Comment by Bill-Fischofer-Linaro** [comment]
I'm not sure how that would happen given the immediately preceding code:

	/* Resolve output buffer */
	if (ODP_PACKET_INVALID == param->out_pkt &&
	    ODP_POOL_INVALID != session->p.output_pool)
		param->out_pkt = odp_packet_alloc(session->p.output_pool,
				odp_packet_len(param->pkt));

	if (odp_unlikely(ODP_PACKET_INVALID == param->out_pkt)) {
		ODP_DBG("Alloc failed.\n");
		return -1;
	}

If out_pkt is invalid the call should simply fail with a -1 return.

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro it will, if `session->p.output_pool` is not ODP_POOL_INVALID.

**Comment by Bill-Fischofer-Linaro** [comment]
If session->p.output_pool is not ODP_POOL_INVALID then the attempt to allocate out_pkt from that pool will be made. If that allocation fails then you'd still get a -1 return and out_pkt would still be ODP_PACKET_INVALID.

**Comment by lumag** [comment]
But if out_pool and out_pkt are bot _INVALID, you won't get a packet. You will get a nice crash.

**Comment by Bill-Fischofer-Linaro** [comment]
If out_pkt and pool are both invalid, the allocate call is skipped and then the check to return -1 if out_pkt is invalid should trigger, no?

**Comment by lumag** [comment]
I'd just prefer to check the return of underlying API.

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro  can you please email Review-by to ML. Transfer from email to this page work. Transfer back not yet.

**Comment by Bill-Fischofer-Linaro** [comment]
I've added my Review via the mailing list as well. Thanks.

**Comment by lumag** [comment]
Merged

**Pull request closed without merging**
