### PR TITLE
[PATCH v3] Simplify tests source code by removing separate files with just main function

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by psavol** [comment]
Reviewed-by: Petri Savolainen <petri.savolainen@linaro.org>

Thanks for the clean up ! Those headers and main function c files didn't have any real purpose.

**Comment by psavol** [comment]
Something is wrong with the pktio test. Maybe unroll patch for pktio test and merge all others first, assuming those work OK as majority is just removal of unnecessary function prototypes and files. Packet IO testing is bit more complex with scripting involved.

FAILURE detected at ./platform/linux-generic/test/validation/api/pktio/pktio_run_netmap.trs
running with pktio_main: ./validation/api/pktio/../../../../../../test/validation/api/pktio/pktio_main
Segmentation fault (core dumped)
!!! FAILED !!!

**Comment by lumag** [comment]
@psavol I've partially backed up pktio changes, it should work now.

**Comment by lumag** [comment]
After finishing tfc & checksums I plan to move these files up one level, so that it would be possible to speed up compilation a bit by parallel-making all (most) API test programs.

**Comment by muvarov** [comment]
Plan to have these main()s was to have test library with all linked tests. I.e. there should be small app and test library which tests everything and prints some results. It looks like that is not needed to anyone now. But I prefer to double check that on arch talk before merge.

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro @muvarov rebased.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
