### PR TITLE
[PATCH v1] linux-gen: netmap: fix incorrect debug message

### PR DESCRIPTION
**Pull request by matiaselo**
Move debug message to the correct code branch and add more debug info.

Signed-off-by: Matias Elo <matias.elo@nokia.com>

### CODE REVIEW

**Comment by muvarov** [comment]
`Reported-by: Gyanesh Patra  <pgyanesh.patra@gmail.com>`

**Comment by matiaselo** [comment]
> Reported-by: Gyanesh Patra <pgyanesh.patra@gmail.com>

@muvarov Can you add that to the commit log or do I send V2?

**Comment by muvarov** [comment]
yes, just added it here to not forget. No need to rebase.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
