### PR TITLE
[PATCH v1] example: generator: performance changes

### PR DESCRIPTION
**Pull request by bogdanPricope**
Various changes to increase performance of odp_generator example appliation.

- remove 1 ms sleep on send loop
- increase maximum TX burst size to 512
- add configuration option for checksum support
- replace atomic counter with per worker counters

### CODE REVIEW

**Comment by muvarov** [comment]
did you test that in lava?

**Comment by bogdanPricope** [comment]
https://lng.validation.linaro.org/scheduler/job/23341.1
https://lng.validation.linaro.org/scheduler/job/23341.0

**Comment by muvarov** [comment]
@bogdanPricope  base PR is merged. This needs to go to api-next, not for master. (relays on api changes commit). Can you please rebase this PR?

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
