### PR TITLE
[PATCH v1] travis: fix DOCKER_NAMESPACE variable setting

### PR DESCRIPTION
**Pull request by lumag**
First, original commit missed one quote mark. Second, conditional ifs do
not work in env: part of .travis.yml. Set DOCKER_NAMESPACE properly.

Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>
Fixes: 989df5d2f97ab4711328b11282dcc743f5740e00

### CODE REVIEW

**Comment by muvarov** [comment]
1. Do you use some other bash where that syntax is not working? For me it works.
```
#if [ -z ]; then echo works; fi
#works
```
2. it current Travis run that variable is set correctly where it's used. Please take a look at logs:
https://travis-ci.org/Linaro/odp/builds/420621773

**Comment by lumag** [comment]
@muvarov 

 - It's YML, not bash

- Try overriding variable for your own tree, you'll if it works or not.

**Comment by muvarov** [comment]
@lumag yes,  env really do not inherit.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
