### PR TITLE
[PATCH API-NEXT v2] IPsec API update

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by lumag** [comment]
@bala-manoharan could you please be more specific, what is the issue with commit message? Second patch bears the `api, linux-gen: ` prefix

**Comment by Bill-Fischofer-Linaro** [comment]
Normally API patches would be separate, however in this case bisectability requires that the `const` qualifier be applied to both the API and the implementation, so I don't see a problem here.

**Comment by bala-manoharan** [comment]
@lumag The commit message seems little odd to me. Since this is mainly an api change I would suggest naming the commit as "api: ipsec: ..." the description can have the details of linux-generic changes...

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
