### PR TITLE
[PATCH v2] First set of patches for TigerMoth RC1

### PR DESCRIPTION
**Pull request by lumag**
This is the first set of paches cherry-picked from api-next for TigerMoth. I have tried to select IPsec + crypto changes + their dependencies. This is submitted as a PR to master branch, but should go instead to next branch.

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Not sure what the purpose of this PR is. @muvarov has already moved the api-next branch to next in preparation for creating the TigerMoth_RC1 release.

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro currently `next` is just our plain old `api-next` with tons of merges and duplicate commits. Maxim agreed that I will restructure api-next to cleaner sets of commits.

**Comment by Bill-Fischofer-Linaro** [comment]
Ok, will discuss with @muvarov on Wednesday. Presumably this shouldn't affect the change log.

**Comment by lumag** [comment]
It should not.
BTW: do we plan to merge libconfig+modules into TigerMoth?

**Comment by lumag** [comment]
Replaced with #371  -- full set of patches from api-next.

**Pull request closed without merging**
