### PR TITLE
[PATCH v13] Shippable: fix tests statistics

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by muvarov** [comment]
gcovr: error: no such option: --exclude-dir

**Comment by lumag** [comment]
It seems that enabling code coverage with clang causes build timeouts. I'll update test to enable coverate only for gcc.

**Comment by muvarov** [comment]
where coverage results uploaded and how to see them?

**Comment by lumag** [comment]
@muvarov see screenshot
stats2

**Comment by muvarov** [comment]
@lumag in coverage I see only stats for each file. But I can not click to file and look to functions. Is that expected?

**Comment by lumag** [comment]
@muvarov I don't know, I never used Shippable before. I also see stats for individual files, but no details

**Comment by lumag** [comment]
@muvarov are there any remaining comments/issues with this PR?

**Comment by muvarov** [comment]
@lumag  I'm not sure if we need stats if we can not look into details. It just increase test functionality which we will have to maintain. I would keep coverage tests in Travis until there will be any issues.

**Comment by lumag** [comment]
@muvarov dropped code coverage part

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
