### PR TITLE
[PATCH v2] Pktrefs opt

### PR DESCRIPTION
**Pull request by Bill-Fischofer-Linaro**
Optimizations to the zero-copy packet reference code to partially address issues raised in
https://bugs.linaro.org/show_bug.cgi?id=3201

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v2: Verified that one of the issues is that the ref_count was in a different cache line
than frame_len, so swap ref_count for unshared_len since that's used in non-reference paths.
This should provide additional odp_bench_packet gains.

**Comment by muvarov** [comment]
<pre>From: Maxim Uvarov <maxim.uvarov@linaro.org>
 that can be applied, does anybody have objections?

Maxim.

On 08/15/17 01:00, Github ODP bot wrote:
> Optimizations to the zero-copy packet reference code to partially address issues raised in
> https://bugs.linaro.org/show_bug.cgi?id=3201
> 
> ----------------github------------------------
> /** Email created from pull request 125 (Bill-Fischofer-Linaro:pktrefs-opt)
>  ** https://github.com/Linaro/odp/pull/125
>  ** Patch: https://github.com/Linaro/odp/pull/125.patch
>  ** Base sha: 90d4ce1b3b25ca18446131906007571cc0ed0191
>  ** Merge commit sha: 6d464aeb30e24833ae787e3997a411103c16c70c
>  **/
> ----------------/github------------------------
> 
> ----------------checkpatch.pl------------------------
> total: 0 errors, 0 warnings, 0 checks, 7 lines checked
> 
> 
> to_send-p-000.patch has no obvious style problems and is ready for submission.
> total: 0 errors, 0 warnings, 0 checks, 50 lines checked
> 
> 
> to_send-p-001.patch has no obvious style problems and is ready for submission.
> total: 0 errors, 0 warnings, 0 checks, 46 lines checked
> 
> 
> to_send-p-002.patch has no obvious style problems and is ready for submission.
> ----------------/checkpatch.pl------------------------
> 

 </pre>

**Comment by muvarov** [comment]
<pre>From: Bill Fischofer <bill.fischofer@linaro.org>
 It certainly does no harm and locally it seems to improve performance for
me. Waiting for feedback from Petri, however he indicated that he's in the
midst of another re-write of the packet internals so I leave it up to him
to say whether merging this helps or hinders that effort. It should be
trivial to rebase this on top of whatever improvements Petri has if that's
more convenient.

On Thu, Aug 17, 2017 at 8:50 AM, Maxim Uvarov <maxim.uvarov@linaro.org>
wrote:

> that can be applied, does anybody have objections?
>
> Maxim.
>
> On 08/15/17 01:00, Github ODP bot wrote:
> > Optimizations to the zero-copy packet reference code to partially
> address issues raised in
> > https://bugs.linaro.org/show_bug.cgi?id=3201
> >
> > ----------------github------------------------
> > /** Email created from pull request 125 (Bill-Fischofer-Linaro:
> pktrefs-opt)
> >  ** https://github.com/Linaro/odp/pull/125
> >  ** Patch: https://github.com/Linaro/odp/pull/125.patch
> >  ** Base sha: 90d4ce1b3b25ca18446131906007571cc0ed0191
> >  ** Merge commit sha: 6d464aeb30e24833ae787e3997a411103c16c70c
> >  **/
> > ----------------/github------------------------
> >
> > ----------------checkpatch.pl------------------------
> > total: 0 errors, 0 warnings, 0 checks, 7 lines checked
> >
> >
> > to_send-p-000.patch has no obvious style problems and is ready for
> submission.
> > total: 0 errors, 0 warnings, 0 checks, 50 lines checked
> >
> >
> > to_send-p-001.patch has no obvious style problems and is ready for
> submission.
> > total: 0 errors, 0 warnings, 0 checks, 46 lines checked
> >
> >
> > to_send-p-002.patch has no obvious style problems and is ready for
> submission.
> > ----------------/checkpatch.pl------------------------
> >
>
>
 </pre>

**Comment by Bill-Fischofer-Linaro** [comment]
Superseded by PR #170

**Pull request closed without merging**
