### PR TITLE
[PATCH v2] TigerMoth RC1 patches

### PR DESCRIPTION
**Pull request by lumag**
This is the api-next branch reworked to apply cleanly on top of master. Duplicate commits, merge commits, etc are removed. This should ease branching of TigerMoth RC1.

### CODE REVIEW

**Comment by muvarov** [comment]
grate work!

**Comment by lumag** [comment]
@muvarov updated branch to use linaro address as committer, not gmail. No functional changes.
@Bill-Fischofer-Linaro do we plan to merge modules (https://github.com/Linaro/odp/pull/371/commits/584d294aae82eede0a591104d9a495695b9546cf and related libconfig patches) support at this moment, or later, when DDF and MF will be going in?

**Comment by muvarov** [comment]
@lumag  I would filer out modules. I think I can merge this tree to next branch.  next can be rebased. So I can remove patches from there is needed.

**Comment by lumag** [comment]
Yep. Just use it as 'next'. Modules are last 4 commits, so you can remove them.

**Comment by muvarov** [comment]
Merged to next without the latest 3 commits about odp.conf

**Pull request closed without merging**
