### PR TITLE
[PATCH v3] linux-gen: parse command line options before adding signal handlers.

### PR DESCRIPTION
**Pull request by apalos**
Solves https://bugs.linaro.org/show_bug.cgi?id=3024

Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
I'm not sure what this PR is supposed to do. After applying it I get the following:

```
bill@Ubuntu64:~/linaro/tmfix/example/traffic_mgmt$ ./odp_traffic_mgmt 
HW time counter freq: 3990770008 hz

_ishm.c:880:_odp_ishm_reserve():No huge pages, fall back to normal pages. check: /proc/sys/vm/nr_hugepages.
 PKTIO: initialized loop interface.
 PKTIO: initialized pcap interface.
 PKTIO: initialized ipc interface.
 PKTIO: initialized socket mmap, use export ODP_PKTIO_DISABLE_SOCKET_MMAP=1 to disable.
 PKTIO: initialized socket mmsg,use export ODP_PKTIO_DISABLE_SOCKET_MMSG=1 to disable.
traffic_generator odp_tm_enq_errs=0
pkts_into_tm=1000 pkts_from_tm=1000
./odp_traffic_mgmt(+0x4f55)[0x558156c19f55]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11670)[0x7f82832c9670]
bill@Ubuntu64:~/linaro/tmfix/example/traffic_mgmt$ /lib/x86_64-linux-gnu/libpthread.so.0(accept+0x10)[0x7f82832c8920]
./odp_traffic_mgmt(+0x233cd)[0x558156c383cd]
./odp_traffic_mgmt(+0x72d7)[0x558156c1c2d7]
./odp_traffic_mgmt(+0x4247)[0x558156c19247]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f8282f113f1]
./odp_traffic_mgmt(+0x4dba)[0x558156c19dba]
Received signal=15 (SIGTERM) exiting.
```
Without this patch I get this:

```
bill@Ubuntu64:~/linaro/odp/example/traffic_mgmt$ ./odp_traffic_mgmt 
HW time counter freq: 3990774118 hz

_ishm.c:880:_odp_ishm_reserve():No huge pages, fall back to normal pages. check: /proc/sys/vm/nr_hugepages.
 PKTIO: initialized loop interface.
 PKTIO: initialized pcap interface.
 PKTIO: initialized ipc interface.
 PKTIO: initialized socket mmap, use export ODP_PKTIO_DISABLE_SOCKET_MMAP=1 to disable.
 PKTIO: initialized socket mmsg,use export ODP_PKTIO_DISABLE_SOCKET_MMSG=1 to disable.
traffic_generator odp_tm_enq_errs=0
pkts_into_tm=1000 pkts_from_tm=1000
./odp_traffic_mgmt(+0x4f85)[0x558ffd330f85]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11670)[0x7f0f6e868670]
/lib/x86_64-linux-gnu/libpthread.so.0(accept+0x10)[0x7f0f6e867920]
./odp_traffic_mgmt(+0x233fd)[0x558ffd34f3fd]
./odp_traffic_mgmt(+0x7307)[0x558ffd333307]
./odp_traffic_mgmt(+0x419f)[0x558ffd33019f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f0f6e4b03f1]
./odp_traffic_mgmt(+0x4dea)[0x558ffd330dea]
Received signal=15 (SIGTERM) exiting.bill@Ubuntu64:~/linaro/odp/example/traffic_mgmt$ 
```
So no obvious difference. Am I missing something?

**Comment by apalos** [comment]
No you are not wrong, this only makes the backtrace go away if invalid arguments are used. I'll update it to check the rest of the cases.

**Comment by Bill-Fischofer-Linaro** [comment]
Commenting out line 644 of `_fdserver.c` restores the correct behavior in the example:

```
bill@Ubuntu64:~/linaro/odp/example/traffic_mgmt$ ./odp_traffic_mgmt 
HW time counter freq: 3990769613 hz

_ishm.c:880:_odp_ishm_reserve():No huge pages, fall back to normal pages. check: /proc/sys/vm/nr_hugepages.
 PKTIO: initialized loop interface.
 PKTIO: initialized pcap interface.
 PKTIO: initialized ipc interface.
 PKTIO: initialized socket mmap, use export ODP_PKTIO_DISABLE_SOCKET_MMAP=1 to disable.
 PKTIO: initialized socket mmsg,use export ODP_PKTIO_DISABLE_SOCKET_MMSG=1 to disable.
traffic_generator odp_tm_enq_errs=0
pkts_into_tm=1000 pkts_from_tm=1000
bill@Ubuntu64:~/linaro/odp/example/traffic_mgmt$ 
```
The bug is due to the fact that both ODP and the application are trying to use signal handlers and are somehow stepping on each other.

**Comment by apalos** [comment]
Removing prctl() from the _fdserver.c just removes callback to odp_traffic_mgmt.c signal_handler(). 
The signal handler is producing those backtrace messages as debug info, they are not necessarily a crash.
I'll check the backtrace and if there's no error message, we don't need to apply this PR.

**Comment by muvarov** [comment]
if you removed backtrace  function than #include <execinfo.h>
is not needed any more. But it's valid case that app request signal.

**Comment by muvarov** [comment]
@apalos 

<pre>
        memset(&signal_action, 0, sizeof(signal_action));
        signal_action.sa_handler = signal_handler;
        sigfillset(&signal_action.sa_mask);
        sigaction(SIGILL,  &signal_action, NULL);
        sigaction(SIGFPE,  &signal_action, NULL);
        sigaction(SIGSEGV, &signal_action, NULL);
        sigaction(SIGTERM, &signal_action, NULL);
        sigaction(SIGBUS,  &signal_action, NULL);
<pre>

./platform/linux-generic/_fdserver.c:           prctl(PR_SET_PDEATHSIG, SIGTERM);
./platform/linux-generic/odp_timer.c:   sigev.sigev_signo = SIGALRM;

So tm examples deletes previous signals. But looks like it needs only SIGSEGV. 

sigaction(*new, *old_sig); can return old signals. I.e. in general we can call platform internal signal before app signal or after. That will remove app limitation of using signals.

Now let's take a look which signals are currently used:
1. Timer per thread signal. That should not affect us.

2. _fd_server uses such call:
 prctl(PR_SET_PDEATHSIG, SIGTERM);

then it waits forever for socket(). That looks like bad approach and has to be reworked.
I guess recv_fdserver_msg() return code has to be validated and  prctl() has to be removed. I.e. read() will return broken pipe error and you can cleanly exit from child process.

**Comment by apalos** [comment]
No need to merge this, it's solving nothing.

**Pull request closed without merging**
