### PR TITLE
[PATCH v1] Use inlined byteorder functions

### PR DESCRIPTION
**Pull request by psavol**
Define internal version of byteorder functions which are always inlined.

### CODE REVIEW

**Comment by lumag** [comment]
Reviewed-by: Dmitry Eremin-Solenikov

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro looks liked Ubuntu downloads are not always available.

**Comment by lumag** [comment]
@muvarov @Bill-Fischofer-Linaro or Travis has issues connecting to it. With #412 build will stop earlier is such cases, so it would be easier to notice and restart the build.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
