### PR TITLE
[PATCH API-NEXT v1] update Linaro Copyrights to 2018 year

### PR DESCRIPTION
**Pull request by muvarov**
Refresh Linaro copyrights to more indicate in source code that ODP code is freshly maintained and developed.

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>

### CODE REVIEW

**Comment by lumag** [comment]
@muvarov well... we did not change all those files in 2018, so technically we should not just extend the copyright. I am not a lawyer though.

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro every each big release.

**Comment by lumag** [comment]
On some projects I used to update copyright when doing major addition to the file.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
