### PR TITLE
[PATCH v5] Travis configuration update

### PR DESCRIPTION
**Pull request by lumag**
Main goal of PR is to enable build-testing of ODP for 32-bit x86 arch.
Side effects:
 - Enable installation and link-testing when cross-compiling
 - Enable c++ test when cross-compiling
 - Fix c&p typo in powerpc test name

### CODE REVIEW

**Comment by muvarov** [comment]
@lumag nice changes. In result matrix some COMPILERS= has quotes and some do not have.

**Comment by lumag** [comment]
@muvarov unfortunately this is required to make it work if compiler consists of several words (like `clang --target=aarch64-linux-gnu` or `gcc -m32`).  In theory I can change that setup to be a proper part of build matrix and derive proper CC/CXX from `gcc`/`clang-3.8` and `${CROSS_ARCH}` as a part of `before_setup` stage. Do you think it would be cleaner?

**Comment by lumag** [comment]
@muvarov see [this build](https://travis-ci.org/lumag/odp/builds/275129273). Is it better?

**Comment by lumag** [comment]
@muvarov [fixed armhf](https://travis-ci.org/lumag/odp/builds/275134177).

**Comment by lumag** [comment]
PR updated to merge cross-compilation into main build matrix.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
