### PR TITLE
[PATCH v3] test : odp_pool_per: fix printf string format

### PR DESCRIPTION
**Pull request by linuxias**
Signed-off-by: Seungha Son <linuxias@gmail.com>

### CODE REVIEW

**Comment by linuxias** [comment]
@Bill-Fischofer-Linaro 
Hello.
Could you help me?
I can't understand why CI build is error.
I think, this is not a problem with this commit when I check the logs.

**Comment by muvarov** [comment]
I re run tests. Problem is that some Ubuntu servers some time are not reachible. There is already PR for that to switch do Docker infrastructure with already installed env. I think we will review it soon and merge, than such errors will go away.

**Comment by linuxias** [comment]
@muvarov @bogdanPricope 
Thanks for your effort.
Please review!

**Comment by linuxias** [comment]
@bogdanPricope 
Aha, thanks.
I have a question. When this commit is merged? Is there anything else I haven't done?

**Comment by bogdanPricope** [comment]
We'll have an "ODP Arch Sync" meeting today (in 3h).  Will be discussed.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
