### PR TITLE
[PATCH v4] More build system improvements

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by muvarov** [comment]
ipc_common.h:23:27: fatal error: example_debug.h: No such file or directory
 #include <example_debug.h>

**Comment by lumag** [comment]
@muvarov fixed

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro I reviewed patches and ok with them. Will you also review?

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
