### PR TITLE
[PATCH v2] travis: doxygen 1.8.13

### PR DESCRIPTION
**Pull request by muvarov**
Update doxygen to 1.8.13

After we fix warnings we can threat warnings as errors. That option is available only in later doxygen releases.

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>

### CODE REVIEW

**Comment by lumag** [comment]
Could you please add it to cache?

**Comment by muvarov** [comment]
@lumag to add it to cache we need to install doxygen to some directory and add to odp config option to specify where is doxygen. Cache will save about 1 minute of execution. Probably there is some m4 macros already exist to point to installed doxygen directory.

**Comment by muvarov** [comment]
@lumag @Bill-Fischofer-Linaro  doxygen m4 macros does not have option to specify directory of where is it installed. I will try to play with it, maybe simple path will be enough.

**Comment by lumag** [comment]
Looks good now, thank you!
Reviewed-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
