### PR TITLE
[PATCH API-NEXT v2] Pkt remove unshared

### PR DESCRIPTION
**Pull request by Bill-Fischofer-Linaro**
Per @psavol suggestion, remove the `odp_packet_unshared_len()` API, along with its associated implementation, validation tests, and documentation.

This is issued against api-next, which is still having Travis build issues. I'll rebase once that's been sorted out.

### CODE REVIEW

**Comment by bala-manoharan** [comment]
Reviewed-by: Balasubramanian Manoharan <bala.manoharan@linaro.org>

**Comment by Bill-Fischofer-Linaro** [comment]
Only concern with this change is that we're removing an API we've already released in ODP v1.15.0.0 without first deprecating it. Is that something we want to do?

**Comment by psavol** [comment]
I think deprecation is not needed. It's not something application really needs and it's not part of Monarch or Tigermoth.

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v2:

* Rebased to pick up Travis fixes

**Comment by NikhilA-Linaro** [comment]
Reviewed-by: Nikhil Agarwal <nikhil.agarwal@linaro.org>

**Comment by Bill-Fischofer-Linaro** [comment]
@muvarov @psavol @bala-manoharan and @NikhilA-Linaro have all reviewed, so this should be good to merge.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
