### PR TITLE
[PATCH v1] changelog: addendum for v1.19.0.2

### PR DESCRIPTION
**Pull request by Bill-Fischofer-Linaro**
Document additional changes incorporated in v1.19.0.2 relating to
running ODP on large core count systems.

Signed-off-by: Bill Fischofer <bill.fischofer@linaro.org>

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
@muvarov Looks like the IPC test is still getting intermittent failures?

**Comment by muvarov** [comment]
@Bill-Fischofer-Linaro  looks like yes, but I can not reproduce it locally.

**Comment by Bill-Fischofer-Linaro** [comment]
@muvarov We can either restart that test and I suspect it will pass or ignore it for merge, whichever you prefer.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
