### PR TITLE
[PATCH API-NEXT v7] patches from master -> api-next

### PR DESCRIPTION
**Pull request by muvarov**
First step is to update current api-next with patches from master. Second step will be move api-next patches to master. It's better to have updated branches to use git diff for finding differencies.

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Travis seems to have a number of issues with this. Not sure if a clean Travis run is expected here.

**Comment by matiaselo** [comment]
The problem is `odp_scheduling_run_proc.sh`, which should be removed. This script tries to run `odp_scheduling` performance test in process mode without a separate config file, which leads to a failure due to running out of single va memory. `odp_scheduling` test is run in process mode in Travis process_mode test phase.

**Comment by matiaselo** [comment]
Travis passes after these two changes: https://github.com/matiaselo/odp/commits/review/test_next

**Comment by muvarov** [comment]
@matiaselo  one more problem is dpdk zero copy and ./odp_sched_pktio_run.sh test. Or it needs 2000 2M hugepages to run or pool size should be lowered. Problem is that DPDK can not do it's init and pool creation for zero copy fails.

**Comment by matiaselo** [comment]
> @matiaselo one more problem is dpdk zero copy and ./odp_sched_pktio_run.sh test. Or it needs 2000 2M hugepages to run or pool size should be lowered. Problem is that DPDK can not do it's init and pool creation for zero copy fails.

@muvarov Did you revert the single va memory config changes? For me Travis is passing after that: https://github.com/matiaselo/odp/commits/review/test_next

**Comment by muvarov** [comment]
Short summary. This patchset has 5 new commits:
https://github.com/Linaro/odp/pull/760/commits/9efdbaac749a5d9d76bd09957e69af04a282ad01
https://github.com/Linaro/odp/pull/760/commits/8fb366ee1af66670cb0e3f8246459e92a7c8671c
https://github.com/Linaro/odp/pull/760/commits/f722cfa060d21f49406ef50963d3d4588d9925d1
https://github.com/Linaro/odp/pull/760/commits/5052617e7dcfbea95b94eb9d7c5fab4cbe810c08
https://github.com/Linaro/odp/pull/760/commits/acdde410b0007a1cdabfa5d9ede6847b4f51d68d

All other 32 patches are patches from master.

**Comment by lumag** [comment]
Well, shouldn't api-next be rebased on top of master, as we did several times during the last year?

**Comment by muvarov** [comment]
@lumag yes, did that in next PR. Here I just put patches on top. Might be it's not good solution. Usually we do rebase just after release.

**Comment by muvarov** [comment]
@matiaselo  v7 added "linux-gen: drop performance.m4" patch.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
