### PR TITLE
[PATCH v3] shippable: switch to using official Shippable image

### PR DESCRIPTION
**Pull request by lumag**
Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Update: I've verified that adding `--disable-test-cpp` doesn't change this behavior. When compiling with the newer clang, `--disable-abi-compat` seems to require that `-fPIC` be used to avoid this abort. Not sure what other applications besides the traffic manager example are affected by this.

**Comment by lumag** [comment]
@muvarov could you `git bisect` that commit range?

**Comment by lumag** [comment]
Also it might be interesting to compare assembly outputs.

**Comment by muvarov** [comment]
I bissected and commit where test fails is fd383ebb6ea70350c28227d0b133c4e9c7075997
which enables march=native
 configure.ac
ODP_CHECK_CFLAG([-march=native])

**Comment by muvarov** [comment]
https://pastebin.linaro.org/view/3e1d886d   diff -Nuarp  dis_no-march-native.log dis_march-native.log

**Comment by lumag** [comment]
Let's put this `ODP_CHECK_CFLAG` under !clang for now.

**Comment by muvarov** [comment]
Merged

**Pull request closed without merging**
