### PR TITLE
[PATCH v2] Fix check-valgrind invocation

### PR DESCRIPTION
**Pull request by lumag**
Fixes https://bugs.linaro.org/show_bug.cgi?id=2254

### CODE REVIEW

**Comment by muvarov** [comment]
make check-valgrind does not execute anything for me.

**Comment by muvarov** [comment]
that change is ok,  but I think we need a little bit clean up before merging. At least exclude bash files from execution.

**Comment by lumag** [comment]
@muvarov no, there is no point in removing shell scripts from execution. valgrind will check both shell and underlying programs.

**Comment by muvarov** [comment]
@lumag we do not need to debug memory leaks inside bash or any other test case. I think we only take care about our test code.

**Comment by lumag** [comment]
What would you prefer from:
 - Being able to valgrind tests (maybe having false positives thanks to bash)
 - Not being able to valgrind tests in automatic way?

**Comment by muvarov** [comment]
@lumag yea, looks like it's trade off. I'm going to merge this and when  I will have some ideas how to put this to Travis - it will be separate patch.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
