### PR TITLE
[PATCH v4] some fixes for ishm

### PR DESCRIPTION
**Pull request by joseppc**

### CODE REVIEW

**Comment by muvarov** [comment]
patch short description has to be "linux-gen: shm: fix ......"

**Comment by joseppc** [comment]
All patches have their corresponding description...

**Comment by joseppc** [comment]
Is there something I have to do regarding the warning "The target branch requires all commits to be signed"?

**Comment by muvarov** [comment]
@joseppc where do you see this warning?

**Comment by joseppc** [comment]
@muvarov here:

Warning

Probably only a message for me :wink:

**Comment by Bill-Fischofer-Linaro** [comment]
@joseppc No, I see that too, I just didn't read it before. All of the patches are signed so I'm not sure where that's coming from.

**Comment by muvarov** [comment]
@joseppc  it said that commit needs to be signed with PGP keys. That is not needed for ODP. I removed this requirement from project settings.  Looks like it's new functionality on web interface.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
