### PR TITLE
[PATCH v1] helper: move include files to helper/include

### PR DESCRIPTION
**Pull request by lumag**
Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by lumag** [comment]
This fixes https://bugs.linaro.org/show_bug.cgi?id=3216

**Comment by muvarov** [comment]
@lumag  at the some time we need to add this option to .travis.yaml

**Comment by muvarov** [comment]
@lumag patch is merged. I do not close PR before we have a test for that option.

**Comment by Bill-Fischofer-Linaro** [comment]
This also needs to be added to api-next as the same bug is present in that branch.

**Comment by muvarov** [comment]
@lumag pr can be closed, right?

**Comment by lumag** [comment]
Yes, closing

**Pull request closed without merging**
