### PR TITLE
[PATCH API-NEXT v1] RFC: linux-generic: queue: modular queue interface

### PR DESCRIPTION
**Pull request by nagarahalli**
RFC for modular queue interface using odp_queue_t towards internal ODP
components. There is no internal abstract queue type.

Signed-off-by: Honnappa Nagarahalli <honnappa.nagarahalli@arm.com>

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Patch has whitespace issues that should be fixed. Scalable scheduler patch applies but is broken with this RFC, so that would need a v9.

**Comment by nagarahalli** [comment]
@Bill-Fischofer-Linaro It looks to be a GitHub issue. For ex: it shows the whitespace issues in odp_queue_if.h file, but in my local copy, those issues are not present. Checkpatch also does not report any errors (I have checked-in a temp file which the checkpatch is complaining about, I will remove that in the next version).

**Comment by Bill-Fischofer-Linaro** [comment]
If I download the patch checkpatch shows the same whitespace errors for me. You might want to double check the files before pushing them.

**Comment by muvarov** [comment]
<pre>From: Maxim Uvarov <maxim.uvarov@linaro.org>
 On 06/19/17 08:00, Github ODP bot wrote:
>  log                                                | 1269 ++++++++++++++++++++

log has not be a part of patch.

Maxim.
 </pre>

**Pull request closed without merging**
