### PR TITLE
[PATCH 2.0 v1] Api next merge to 2.0

### PR DESCRIPTION
**Pull request by heyi-linaro**
- Build linux-dpdk with 17.02 and linux-generic with dpdk 17.08 (temporary travis solution)
- Fix ipsec build in linux-dpdk platform by adding sources/functions
- Fix linux-dpdk build with Dimitry's build system updates
- Fix make checks and distcheck

### CODE REVIEW

**Comment by heyi-linaro** [comment]
@GBalakrishna and @nagarahalli will you have a review.

**Comment by heyi-linaro** [comment]
Github seems cannot show merging changes properly for reviewers, it shows all changes of whole commits.

**Comment by nagarahalli** [comment]
The Travis CI build failure is due to check patch failures, which is a known issue with PRs for api-next merge. Otherwise, all the tests are passing fine. Looks good to me.

**Comment by nagarahalli** [comment]
I see Shippable CI is running, but it is having segmentation fault in few test cases.

**Comment by heyi-linaro** [comment]
Merged and closed.

**Pull request closed without merging**
