### PR TITLE
[PATCH v1] travis: split build into separate stages

### PR DESCRIPTION
**Pull request by lumag**
Introduce separate parallel builds for checkpatch, doxygen, distcheck
and plain checks.

Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by lumag** [comment]
Got timeout in pktio_run_pcap.sh test when built for coverage analysis. Any idea?

**Comment by lumag** [comment]
Moreover, the test works correctly if running with serial automake driver. It looks like some kind of interference of parallel ODP applications.

**Comment by lumag** [comment]
Should be fixed by #41

**Comment by muvarov** [comment]
@lumag looks nice. In the Travis test table we need some readable note about what is the current stage is. I found that we can only set environment variable. Even if we do not use it. Like STAGE=DISTCHECK

**Comment by muvarov** [comment]
@lumag yes, looks like if we run test in parallel then we can not delete shm, ipc passed but other test might hang.

**Comment by lumag** [comment]
@muvarov If we really need to delete IPC, this should be done from whithin the program, when we know the PID. Or we should stop hardcoding /tmp.

**Comment by lumag** [comment]
I'll update adding 'environment' names.

**Comment by muvarov** [comment]
@lumag maybe combine it with the same time with #36 ? I think pr will overlap.

**Pull request closed without merging**
