### PR TITLE
[PATCH API-NEXT v3] linux-gen: drop leftover headers

### PR DESCRIPTION
**Pull request by lumag**
Drop headers moved to /include in master, which reappeared in api-next.

Fixes: f925f103c90591776f73863d30159357b08bf71e
Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>

### CODE REVIEW

**Comment by muvarov** [comment]
@lumag yes, thanks.

**Comment by lumag** [comment]
@muvarov added two more commits, dropping other headers.

**Comment by muvarov** [comment]
Merged.

**Comment by lumag** [comment]
@muvarov you missed one commit. I'm adding another one to the same branch (static_inline.h). Please pick them.

**Pull request closed without merging**
