### PR TITLE
[PATCH v6] Tmfinal changelog

### PR DESCRIPTION
**Pull request by Bill-Fischofer-Linaro**
Changelog for Tiger Moth Final release.

### CODE REVIEW

**Comment by Bill-Fischofer-Linaro** [comment]
Accidentally deleted this PR. Recreated.

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro note, there is a `CHANGELOG` conflict, you might want to rebase this PR.
Otherwise it looks good from my point of view.

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v3
* Rebased to latest master
* Resolved merge conflict due to previous master instability.

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v4:
* Rebased to latest master
* Updated to reflect latest changes and merges
* Reflect final release number v1.19.0.0

**Comment by lumag** [comment]
I thought on Monday we had agreed on 1.18.1.0, didn't we?

**Comment by muvarov** [comment]
@lumag On Monday we spitted between 1.18 and 1.19. Because we have changes in api description we also need to change api version number due to this commit: https://github.com/Linaro/odp/commit/83fda5a447335b95bdd991187d4efb0a15a5709a

We had the same question some times in the past. And decision was to escape double meaning in understanding API definition. Even if we do not change API function. This change clarify exact result which actually provide more strict rules for odp implementation. So in that case we need to follow:
https://www.opendataplane.org/developers/release-guide/index.html
4.3 Minor releases.

**Comment by lumag** [comment]
Reviewed-by: Dmitry Eremin-Solenikov

**Comment by Bill-Fischofer-Linaro** [comment]
Changes for v5:
* Rebased to latest master
* Bug fix list updated to reflect latest pending fix PRs.

**Comment by muvarov** [comment]
Merged.

**Pull request closed without merging**
