### PR TITLE
[PATCH v1] Fix AES-GCM tag check

### PR DESCRIPTION
**Pull request by lumag**

### CODE REVIEW

**Comment by lumag** [comment]
@Bill-Fischofer-Linaro ping
This fixes security issue. Opened a bug at https://bugs.linaro.org/show_bug.cgi?id=3003

**Comment by lumag** [comment]
@muvarov could you please merge this PR?

**Comment by muvarov** [comment]
Merged.

**Comment by lumag** [comment]
@muvarov It had to be merged into master branch, not api-next! Master branch still contains this vulnerability.

BTW: why are you merging PRs by manually applying paches, rather than merging the original branch into it?

**Pull request closed without merging**
